version: "3.8"

services:
 node:
  container_name: "node-learning"
  build:
   dockerfile: "Dockerfile"
   context: "./.docker/node/"
  hostname: "node-learning"
  tty: true
  volumes:
   - "./src:/src"
  ports:
   - "3333:3000"
   - "9229:9229"
  environment:
   - "CHOKIDAR_USEPOLLING=true"
  networks:
   - "node-turtorial"
 mongod:
  container_name: "mongod"
  image: "mongo:6.0"
  restart: "no"
  volumes:
   - "./.docker/mongo/mongod.conf:/etc/mongod.conf"
   - "./.docker/data:/data/db"
  ports:
   - "27017:27017"
  environment:
   - "MONGO_INITDB_ROOT_USERNAME=admin"
   - "MONGO_INITDB_ROOT_PASSWORD=admin"
  networks:
   - "node-turtorial"
 mongo-express:
  container_name: "mongo-express"
  image: "mongo-express:1.0.0-alpha.4"
  restart: "no"
  ports:
   - "8081:8081"
  environment:
   - "ME_CONFIG_MONGODB_SERVER=mongod"
   - "ME_CONFIG_MONGODB_PORT=27017"
   - "ME_CONFIG_MONGODB_ENABLE_ADMIN=true"
   - "ME_CONFIG_MONGODB_ADMINUSERNAME=admin"
   - "ME_CONFIG_MONGODB_ADMINPASSWORD=admin"
   - "ME_CONFIG_BASICAUTH_USERNAME=admin"
   - "ME_CONFIG_BASICAUTH_PASSWORD=admin"
  depends_on:
   - "mongod"
  networks:
   - "node-turtorial"

networks:
 node-turtorial:
  name: "node-turtorial"
  driver: "bridge"